In [330]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [331]:
data = pd.read_csv (r'Basketball.csv')

CLEANING OF THE DATA - replacing any unwanted values, checking for missing values and duplicate name of teams, checking for inconsistencies

In [333]:
data.shape

(61, 13)

In [334]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Team                 61 non-null     object
 1   Tournament           61 non-null     int64
 2   Score                61 non-null     object
 3   PlayedGames          61 non-null     object
 4   WonGames             61 non-null     object
 5   DrawnGames           61 non-null     object
 6   LostGames            61 non-null     object
 7   BasketScored         61 non-null     object
 8   BasketGiven          61 non-null     object
 9   TournamentChampion   61 non-null     object
 10  Runner-up            61 non-null     object
 11  TeamLaunch           61 non-null     object
 12  HighestPositionHeld  61 non-null     int64
dtypes: int64(2), object(11)
memory usage: 6.3+ KB

In [335]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

data

,Team,Tournament,Score,PlayedGames,WonGames,DrawnGames,LostGames,BasketScored,BasketGiven,TournamentChampion,Runner-up,TeamLaunch,HighestPositionHeld
0,Team 1,86,4385,2762,1647,552,563,5947,3140,33,23,1929,1
1,Team 2,86,4262,2762,1581,573,608,5900,3114,25,25,1929,1
2,Team 3,80,3442,2614,1241,598,775,4534,3309,10,8,1929,1
3,Team 4,82,3386,2664,1187,616,861,4398,3469,6,6,1931to32,1
4,Team 5,86,3368,2762,1209,633,920,4631,3700,8,7,1929,1
5,Team 6,73,2819,2408,990,531,887,3680,3373,1,4,1934-35,1
6,Team 7,82,2792,2626,948,608,1070,3609,3889,-,-,1929,3
7,Team 8,70,2573,2302,864,577,861,3228,3230,2,3,1929,1
8,Team 9,58,2109,1986,698,522,766,2683,2847,-,1,1939-40,2
9,Team 10,51,1884,1728,606,440,682,2159,2492,1,-,1932-33,1
10,Team 11,45,1814,1530,563,392,575,2052,2188,1,5,1941to42,1
11,Team 12,51,1789,1698,586,389,723,2278,2624,-,-,1939-40,4
12,Team 13,42,1471,1466,463,384,619,1767,2180,-,-,1948-49,4
13,Team 14,44,1416,1428,453,336,639,1843,2368,-,1,1929,2
14,Team 15,43,1389,1458,471,358,629,1753,2152,-,1,1944_45,2
15,Team 16,37,1351,1318,426,327,565,1500,1834,-,-,1935-36,4
16,Team 17,36,1314,1255,390,330,535,1421,1763,-,-,1949_50,4
17,Team 18,38,1174,1192,408,292,492,1642,1951,-,-,1933to34,3
18,Team 19,27,1148,988,333,256,399,1182,1371,-,-,1960-61,3
19,Team 20,33,1020,1096,367,242,487,1347,1746,-,1,1951-52,2
20,Team 21,17,970,646,266,172,208,892,789,-,1,1998-99,2
21,Team 22,23,667,742,218,175,349,819,1157,-,-,1941-42,6
22,Team 23,17,662,652,189,148,305,760,1088,-,-,1977-78,8
23,Team 24,21,606,678,203,180,295,750,1022,-,-,1959-60,5
24,Team 25,12,553,456,147,112,197,520,633,-,-,2004to05,6
25,Team 26,20,538,628,184,149,295,716,1050,-,-,1935-36,5
26,Team 27,13,510,494,155,128,211,619,744,-,-,1961-62,5
27,Team 28,18,445,586,145,143,298,607,992,-,-,1940-41,11
28,Team 29,12,421,380,125,81,174,458,623,-,-,1930-31,6
29,Team 30,11,416,402,113,95,194,430,632,-,-,1963-64,6
30,Team 31,12,375,423,123,102,198,422,581,-,-,1974-75,7
31,Team 32,14,353,426,129,95,202,492,720,-,-,1943-44,4
32,Team 33,12,343,448,104,127,217,393,662,-,-,1977-78,12
33,Team 34,9,293,346,96,92,158,291,489,-,-,1987-88,7
34,Team 35,11,285,334,103,79,152,419,588,-,-,1941-42,4
35,Team 36,7,277,270,76,76,118,320,410,-,-,1991_92,7
36,Team 37,6,242,228,62,56,110,244,366,-,-,2007-08,8
37,Team 38,9,230,282,82,63,137,285,430,-,-,1962-63,5
38,Team 39,4,190,160,52,45,63,199,241,-,-,1994-95,10
39,Team 40,5,188,186,50,46,90,202,296,-,-,1978-79,8
40,Team 41,6,168,204,59,50,95,216,310,-,-,1971-72,12
41,Team 42,6,150,180,53,44,83,165,221,-,-,1963-64,7
42,Team 43,4,148,152,37,37,78,155,253,-,-,1999to00,17
43,Team 44,3,132,114,35,27,52,139,167,-,-,2014-15,10
44,Team 45,7,107,130,43,21,66,227,308,-,-,1929,3
45,Team 46,3,96,114,26,44,44,101,139,-,-,1990-91,9
46,Team 47,4,91,116,34,16,66,181,295,-,-,1947-48,7
47,Team 48,2,83,80,20,23,37,62,117,-,-,1996-97,17
48,Team 49,2,81,80,19,24,37,70,115,-,-,1995-96,19
49,Team 50,4,76,108,30,16,62,145,252,-,-,1945-46,10
50,Team 51,3,71,90,29,13,48,121,183,-,-,1953-54,14
51,Team 52,4,56,72,21,14,37,153,184,-,-,1929,6
52,Team 53,2,52,68,17,18,33,71,116,-,-,1979-80,10
53,Team 54,3,42,54,18,6,30,97,131,-,-,1929,8
54,Team 55,2,40,68,13,14,41,70,182,-,-,1950-51,16
55,Team 56,1,35,38,8,11,19,36,55,-,-,2016_17,17
56,Team 57,1,34,38,8,10,20,38,66,-,-,2009-10,20
57,Team 58,1,22,30,7,8,15,37,57,-,-,1956-57,16
58,Team 59,1,19,30,7,5,18,51,85,-,-,1951~52,16
59,Team 60,1,14,30,5,4,21,34,65,-,-,1955-56,15
60,Team 61,1,-,-,-,-,-,-,-,-,-,2017~18,9

In [336]:
data.columns

Index(['Team', 'Tournament', 'Score', 'PlayedGames', 'WonGames', 'DrawnGames',
       'LostGames', 'BasketScored', 'BasketGiven', 'TournamentChampion',
       'Runner-up', 'TeamLaunch', 'HighestPositionHeld'],
      dtype='object')

In [337]:
cols = ['Tournament', 'Score', 'PlayedGames', 'WonGames', 'DrawnGames',
       'LostGames', 'BasketScored', 'BasketGiven', 'TournamentChampion',
       'Runner-up', 'HighestPositionHeld']

In [338]:
#convert most columns to numerical datatype
data[cols] = data[cols].apply(pd.to_numeric, axis=1,errors = 'coerce')

In [371]:
#checking for any null values in the dataset
data.isnull().sum()

TeamName                    0
PlayedTournaments           0
Score                       0
PlayedGames                 0
WonGames                    0
DrawnGames                  0
LostGames                   0
BasketScored                0
BasketGiven                 0
TournamentChampion          0
Runnerup                    0
TeamLaunch                  0
HighestPositionHeld         0
PlayedGamesperTournament    0
WonGamesperTournament       0
DrawnGamesperTournament     0
LostGamesperTournament      0
dtype: int64

In [340]:
#listing teams who have not played any games, as they wont add any value to the report
data  = data.dropna(subset='PlayedGames')

In [341]:
#replace the NULL values with 0
data.replace(to_replace=np.nan, value =0, inplace= True)

/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/1420190965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.replace(to_replace=np.nan, value =0, inplace= True)

In [342]:
#rename a few columns correctly
data.rename(columns={'Tournament':'PlayedTournaments', 'Team':'TeamName','Runner-up':'Runnerup'},inplace= True)

/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/1768448428.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns={'Tournament':'PlayedTournaments', 'Team':'TeamName','Runner-up':'Runnerup'},inplace= True)

In [343]:
data.describe()

,PlayedTournaments,Score,PlayedGames,WonGames,DrawnGames,LostGames,BasketScored,BasketGiven,TournamentChampion,Runnerup,HighestPositionHeld
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.00000,60.000000,60.000000
mean,24.383333,916.450000,810.100000,309.033333,192.083333,308.816667,1159.350000,1159.233333,1.45000,1.433333,7.050000
std,26.884620,1138.342899,877.465393,408.481395,201.985508,294.508639,1512.063948,1163.946914,5.51554,4.574679,5.315232
min,1.000000,14.000000,30.000000,5.000000,4.000000,15.000000,34.000000,55.000000,0.00000,0.000000,1.000000
25%,4.000000,104.250000,115.500000,34.750000,26.250000,62.750000,154.500000,236.000000,0.00000,0.000000,3.000000
50%,12.000000,395.500000,424.500000,124.000000,98.500000,197.500000,444.000000,632.500000,0.00000,0.000000,6.000000
75%,39.000000,1360.500000,1345.500000,432.750000,331.500000,563.500000,1669.750000,2001.250000,0.00000,0.000000,10.000000
max,86.000000,4385.000000,2762.000000,1647.000000,633.000000,1070.000000,5947.000000,3889.000000,33.00000,25.000000,20.000000

In [344]:
#checking for any duplicate entries for the team name
counts = data['TeamName'].value_counts()
print (counts[counts>1])

Series([], Name: count, dtype: int64)

In [372]:
data.dtypes

TeamName                     object
PlayedTournaments           float64
Score                       float64
PlayedGames                 float64
WonGames                    float64
DrawnGames                  float64
LostGames                   float64
BasketScored                float64
BasketGiven                 float64
TournamentChampion          float64
Runnerup                    float64
TeamLaunch                   object
HighestPositionHeld         float64
PlayedGamesperTournament    float64
WonGamesperTournament       float64
DrawnGamesperTournament     float64
LostGamesperTournament      float64
dtype: object

In [373]:
#considring the earlier avilable year as team launch
data['TeamLaunch'] = data['TeamLaunch'].apply(lambda x :x[0:4])
data

/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/2162419068.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['TeamLaunch'] = data['TeamLaunch'].apply(lambda x :x[0:4])

,TeamName,PlayedTournaments,Score,PlayedGames,WonGames,DrawnGames,LostGames,BasketScored,BasketGiven,TournamentChampion,Runnerup,TeamLaunch,HighestPositionHeld,PlayedGamesperTournament,WonGamesperTournament,DrawnGamesperTournament,LostGamesperTournament
0,Team 1,86.0,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,1929,1.0,32.116279,19.151163,6.418605,6.546512
1,Team 2,86.0,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,1929,1.0,32.116279,18.383721,6.662791,7.069767
2,Team 3,80.0,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,1929,1.0,32.675000,15.512500,7.475000,9.687500
3,Team 4,82.0,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,1931,1.0,32.487805,14.475610,7.512195,10.500000
4,Team 5,86.0,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,1929,1.0,32.116279,14.058140,7.360465,10.697674
5,Team 6,73.0,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,1.0,4.0,1934,1.0,32.986301,13.561644,7.273973,12.150685
6,Team 7,82.0,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,0.0,0.0,1929,3.0,32.024390,11.560976,7.414634,13.048780
7,Team 8,70.0,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,2.0,3.0,1929,1.0,32.885714,12.342857,8.242857,12.300000
8,Team 9,58.0,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,0.0,1.0,1939,2.0,34.241379,12.034483,9.000000,13.206897
9,Team 10,51.0,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,1.0,0.0,1932,1.0,33.882353,11.882353,8.627451,13.372549
10,Team 11,45.0,1814.0,1530.0,563.0,392.0,575.0,2052.0,2188.0,1.0,5.0,1941,1.0,34.000000,12.511111,8.711111,12.777778
11,Team 12,51.0,1789.0,1698.0,586.0,389.0,723.0,2278.0,2624.0,0.0,0.0,1939,4.0,33.294118,11.490196,7.627451,14.176471
12,Team 13,42.0,1471.0,1466.0,463.0,384.0,619.0,1767.0,2180.0,0.0,0.0,1948,4.0,34.904762,11.023810,9.142857,14.738095
13,Team 14,44.0,1416.0,1428.0,453.0,336.0,639.0,1843.0,2368.0,0.0,1.0,1929,2.0,32.454545,10.295455,7.636364,14.522727
14,Team 15,43.0,1389.0,1458.0,471.0,358.0,629.0,1753.0,2152.0,0.0,1.0,1944,2.0,33.906977,10.953488,8.325581,14.627907
15,Team 16,37.0,1351.0,1318.0,426.0,327.0,565.0,1500.0,1834.0,0.0,0.0,1935,4.0,35.621622,11.513514,8.837838,15.270270
16,Team 17,36.0,1314.0,1255.0,390.0,330.0,535.0,1421.0,1763.0,0.0,0.0,1949,4.0,34.861111,10.833333,9.166667,14.861111
17,Team 18,38.0,1174.0,1192.0,408.0,292.0,492.0,1642.0,1951.0,0.0,0.0,1933,3.0,31.368421,10.736842,7.684211,12.947368
18,Team 19,27.0,1148.0,988.0,333.0,256.0,399.0,1182.0,1371.0,0.0,0.0,1960,3.0,36.592593,12.333333,9.481481,14.777778
19,Team 20,33.0,1020.0,1096.0,367.0,242.0,487.0,1347.0,1746.0,0.0,1.0,1951,2.0,33.212121,11.121212,7.333333,14.757576
20,Team 21,17.0,970.0,646.0,266.0,172.0,208.0,892.0,789.0,0.0,1.0,1998,2.0,38.000000,15.647059,10.117647,12.235294
21,Team 22,23.0,667.0,742.0,218.0,175.0,349.0,819.0,1157.0,0.0,0.0,1941,6.0,32.260870,9.478261,7.608696,15.173913
22,Team 23,17.0,662.0,652.0,189.0,148.0,305.0,760.0,1088.0,0.0,0.0,1977,8.0,38.352941,11.117647,8.705882,17.941176
23,Team 24,21.0,606.0,678.0,203.0,180.0,295.0,750.0,1022.0,0.0,0.0,1959,5.0,32.285714,9.666667,8.571429,14.047619
24,Team 25,12.0,553.0,456.0,147.0,112.0,197.0,520.0,633.0,0.0,0.0,2004,6.0,38.000000,12.250000,9.333333,16.416667
25,Team 26,20.0,538.0,628.0,184.0,149.0,295.0,716.0,1050.0,0.0,0.0,1935,5.0,31.400000,9.200000,7.450000,14.750000
26,Team 27,13.0,510.0,494.0,155.0,128.0,211.0,619.0,744.0,0.0,0.0,1961,5.0,38.000000,11.923077,9.846154,16.230769
27,Team 28,18.0,445.0,586.0,145.0,143.0,298.0,607.0,992.0,0.0,0.0,1940,11.0,32.555556,8.055556,7.944444,16.555556
28,Team 29,12.0,421.0,380.0,125.0,81.0,174.0,458.0,623.0,0.0,0.0,1930,6.0,31.666667,10.416667,6.750000,14.500000
29,Team 30,11.0,416.0,402.0,113.0,95.0,194.0,430.0,632.0,0.0,0.0,1963,6.0,36.545455,10.272727,8.636364,17.636364
30,Team 31,12.0,375.0,423.0,123.0,102.0,198.0,422.0,581.0,0.0,0.0,1974,7.0,35.250000,10.250000,8.500000,16.500000
31,Team 32,14.0,353.0,426.0,129.0,95.0,202.0,492.0,720.0,0.0,0.0,1943,4.0,30.428571,9.214286,6.785714,14.428571
32,Team 33,12.0,343.0,448.0,104.0,127.0,217.0,393.0,662.0,0.0,0.0,1977,12.0,37.333333,8.666667,10.583333,18.083333
33,Team 34,9.0,293.0,346.0,96.0,92.0,158.0,291.0,489.0,0.0,0.0,1987,7.0,38.444444,10.666667,10.222222,17.555556
34,Team 35,11.0,285.0,334.0,103.0,79.0,152.0,419.0,588.0,0.0,0.0,1941,4.0,30.363636,9.363636,7.181818,13.818182
35,Team 36,7.0,277.0,270.0,76.0,76.0,118.0,320.0,410.0,0.0,0.0,1991,7.0,38.571429,10.857143,10.857143,16.857143
36,Team 37,6.0,242.0,228.0,62.0,56.0,110.0,244.0,366.0,0.0,0.0,2007,8.0,38.000000,10.333333,9.333333,18.333333
37,Team 38,9.0,230.0,282.0,82.0,63.0,137.0,285.0,430.0,0.0,0.0,1962,5.0,31.333333,9.111111,7.000000,15.222222
38,Team 39,4.0,190.0,160.0,52.0,45.0,63.0,199.0,241.0,0.0,0.0,1994,10.0,40.000000,13.000000,11.250000,15.750000
39,Team 40,5.0,188.0,186.0,50.0,46.0,90.0,202.0,296.0,0.0,0.0,1978,8.0,37.200000,10.000000,9.200000,18.000000
40,Team 41,6.0,168.0,204.0,59.0,50.0,95.0,216.0,310.0,0.0,0.0,1971,12.0,34.000000,9.833333,8.333333,15.833333
41,Team 42,6.0,150.0,180.0,53.0,44.0,83.0,165.0,221.0,0.0,0.0,1963,7.0,30.000000,8.833333,7.333333,13.833333
42,Team 43,4.0,148.0,152.0,37.0,37.0,78.0,155.0,253.0,0.0,0.0,1999,17.0,38.000000,9.250000,9.250000,19.500000
43,Team 44,3.0,132.0,114.0,35.0,27.0,52.0,139.0,167.0,0.0,0.0,2014,10.0,38.000000,11.666667,9.000000,17.333333
44,Team 45,7.0,107.0,130.0,43.0,21.0,66.0,227.0,308.0,0.0,0.0,1929,3.0,18.571429,6.142857,3.000000,9.428571
45,Team 46,3.0,96.0,114.0,26.0,44.0,44.0,101.0,139.0,0.0,0.0,1990,9.0,38.000000,8.666667,14.666667,14.666667
46,Team 47,4.0,91.0,116.0,34.0,16.0,66.0,181.0,295.0,0.0,0.0,1947,7.0,29.000000,8.500000,4.000000,16.500000
47,Team 48,2.0,83.0,80.0,20.0,23.0,37.0,62.0,117.0,0.0,0.0,1996,17.0,40.000000,10.000000,11.500000,18.500000
48,Team 49,2.0,81.0,80.0,19.0,24.0,37.0,70.0,115.0,0.0,0.0,1995,19.0,40.000000,9.500000,12.000000,18.500000
49,Team 50,4.0,76.0,108.0,30.0,16.0,62.0,145.0,252.0,0.0,0.0,1945,10.0,27.000000,7.500000,4.000000,15.500000
50,Team 51,3.0,71.0,90.0,29.0,13.0,48.0,121.0,183.0,0.0,0.0,1953,14.0,30.000000,9.666667,4.333333,16.000000
51,Team 52,4.0,56.0,72.0,21.0,14.0,37.0,153.0,184.0,0.0,0.0,1929,6.0,18.000000,5.250000,3.500000,9.250000
52,Team 53,2.0,52.0,68.0,17.0,18.0,33.0,71.0,116.0,0.0,0.0,1979,10.0,34.000000,8.500000,9.000000,16.500000
53,Team 54,3.0,42.0,54.0,18.0,6.0,30.0,97.0,131.0,0.0,0.0,1929,8.0,18.000000,6.000000,2.000000,10.000000
54,Team 55,2.0,40.0,68.0,13.0,14.0,41.0,70.0,182.0,0.0,0.0,1950,16.0,34.000000,6.500000,7.000000,20.500000
55,Team 56,1.0,35.0,38.0,8.0,11.0,19.0,36.0,55.0,0.0,0.0,2016,17.0,38.000000,8.000000,11.000000,19.000000
56,Team 57,1.0,34.0,38.0,8.0,10.0,20.0,38.0,66.0,0.0,0.0,2009,20.0,38.000000,8.000000,10.000000,20.000000
57,Team 58,1.0,22.0,30.0,7.0,8.0,15.0,37.0,57.0,0.0,0.0,1956,16.0,30.000000,7.000000,8.000000,15.000000
58,Team 59,1.0,19.0,30.0,7.0,5.0,18.0,51.0,85.0,0.0,0.0,1951,16.0,30.000000,7.000000,5.000000,18.000000
59,Team 60,1.0,14.0,30.0,5.0,4.0,21.0,34.0,65.0,0.0,0.0,1955,15.0,30.000000,5.000000,4.000000,21.000000

DATA TRANSFORMATIONS - transforming and normalizing the data for accurate comparisons, removing of outliers

In [374]:
#normalizing the data as different teams have different Played Tournaments
data['PlayedGamesperTournament'] = data['PlayedGames']/ data['PlayedTournaments']
data['WonGamesperTournament'] = data['WonGames']/data['PlayedTournaments']
data['DrawnGamesperTournament'] = data['DrawnGames'] / data['PlayedTournaments']
data['LostGamesperTournament'] = data['LostGames']/data['PlayedTournaments']


new_data = data.drop(columns=['PlayedTournaments','WonGames','DrawnGames','LostGames','PlayedGames'],axis=1)

/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/2529743360.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['PlayedGamesperTournament'] = data['PlayedGames']/ data['PlayedTournaments']
/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/2529743360.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['WonGamesperTournament'] = data['WonGames']/data['PlayedTournaments']
/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/2529743360.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['DrawnGamesperTournament'] = data['DrawnGames'] / data['PlayedTournaments']
/var/folders/qd/0lrktpjd7vx07f15zzz6l5vw0000gn/T/ipykernel_65694/2529743360.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['LostGamesperTournament'] = data['LostGames']/data['PlayedTournaments']

In [375]:
#calculating the number of years the team has played tournaments and sorting based on new teams
new_data['TeamLaunch'] = new_data['TeamLaunch'].apply(pd.to_numeric,errors = "coerce")
new_data['NumberofYears'] = 2024-new_data['TeamLaunch']
drop_data = new_data.drop(columns=['TeamLaunch'],axis=1)
sorted_data = drop_data.sort_values(by = 'NumberofYears',ascending=True)

In [376]:
#transforming the data to percentages
sorted_data['WonPercent'] = (sorted_data['WonGamesperTournament']/sorted_data['PlayedGamesperTournament']) * 100
sorted_data['DrawnPercent'] = (sorted_data['DrawnGamesperTournament']/sorted_data['PlayedGamesperTournament']) * 100
sorted_data['LostPercent'] = (sorted_data['LostGamesperTournament']/sorted_data['PlayedGamesperTournament']) * 100

percent_data = sorted_data.drop (columns=['WonGamesperTournament','DrawnGamesperTournament','LostGamesperTournament','PlayedGamesperTournament'])

In [377]:
#removing of outliers based on the score, basket scored, basket given individually as these would be the teams which would be rather old teams which are mostly bought by other 
# companies
mean_score = percent_data['Score'].mean()
std_score = percent_data['Score'].std()

mean_Basketscored = percent_data['BasketScored'].mean()
std_Basketscored = percent_data['BasketScored'].std()

mean_Basketgiven = percent_data['BasketGiven'].mean()
std_Basketgiven = percent_data['BasketGiven'].std()


percent_data['Z_Score'] = (percent_data['Score']-mean_score)/std_score
percent_data['Z_BasketScored'] = (percent_data['BasketScored'] - mean_Basketscored)/ std_Basketscored
percent_data['Z_Basketgiven'] = (percent_data['BasketGiven'] - mean_Basketgiven) / std_Basketgiven

cleaned_data = percent_data[(np.abs(percent_data['Z_Score'])<=3) & (np.abs(percent_data['Z_BasketScored'])<=3) & (np.abs(percent_data['Z_Basketgiven'])<=3)]

cleaned_data = cleaned_data.drop(columns=['Z_Score','Z_BasketScored','Z_Basketgiven'],axis=1)

In [378]:
#finding whether there are any outliers which might cause disturbance in analysis
cols = ['Score', 'BasketScored', 'BasketGiven',
       'WonPercent', 'DrawnPercent', 'LostPercent']
cleaned_data[cols].skew()

Score           1.479436
BasketScored    1.649563
BasketGiven     1.097300
WonPercent      0.443976
DrawnPercent   -0.452528
LostPercent     0.504693
dtype: float64

FEATURE ENGINEERING - selection of most relevant features for performing the analysis

In [379]:
#selecting the most relevant features and choosing the optimal number of components from the entire data
from sklearn.decomposition import PCA 
from sklearn.preprocessing import StandardScaler

cols = ['Score', 'BasketScored', 'BasketGiven',
       'TournamentChampion', 'Runnerup', 'HighestPositionHeld',
       'NumberofYears', 'WonPercent', 'DrawnPercent', 'LostPercent']

scaler = StandardScaler()
standardised_data = scaler.fit_transform(cleaned_data[cols])

pca = PCA()
principal_data = pca.fit_transform (standardised_data)

explain_variance = pca.explained_variance_ratio_.cumsum()

n_components = np.argmax (explain_variance>=0.95)+1

pca = PCA (n_components= n_components)
reduced_data = pca.fit_transform(standardised_data)
loadings = pca.components_

loadings_df = pd.DataFrame (loadings,columns = cols,index = ['PCA1','PCA2','PCA3','PCA4'])

loadings_df

,Score,BasketScored,BasketGiven,TournamentChampion,Runnerup,HighestPositionHeld,NumberofYears,WonPercent,DrawnPercent,LostPercent
PCA1,0.383861,0.383903,0.368550,0.299002,0.330366,-0.307023,0.225633,0.358949,0.016890,-0.310793
PCA2,0.020229,-0.005081,-0.018000,0.011381,0.018576,0.078923,-0.523801,-0.031811,0.731211,-0.427187
PCA3,0.011962,0.049032,-0.145344,0.598122,0.486643,0.504340,-0.241558,-0.111123,-0.149076,0.185674
PCA4,-0.284996,-0.296950,-0.422692,0.133886,0.108117,-0.369434,-0.283448,0.509173,-0.293587,-0.245029

In [380]:
#finding the sum of each column for the loadings across each principle component
loadingssum = loadings_df.sum()
print (loadingssum)

Score                  0.131057
BasketScored           0.130904
BasketGiven           -0.217485
TournamentChampion     1.042391
Runnerup               0.943702
HighestPositionHeld   -0.093195
NumberofYears         -0.823175
WonPercent             0.725189
DrawnPercent           0.305438
LostPercent           -0.797334
dtype: float64

In [381]:
#we can remove the features that are less than -0.5, as those features do not have much variance from the rest of the features
final_data = cleaned_data.drop(columns=['NumberofYears','LostPercent'],axis=1)
final_data

,TeamName,Score,BasketScored,BasketGiven,TournamentChampion,Runnerup,HighestPositionHeld,WonPercent,DrawnPercent
55,Team 56,35.0,36.0,55.0,0.0,0.0,17.0,21.052632,28.947368
43,Team 44,132.0,139.0,167.0,0.0,0.0,10.0,30.701754,23.684211
56,Team 57,34.0,38.0,66.0,0.0,0.0,20.0,21.052632,26.315789
36,Team 37,242.0,244.0,366.0,0.0,0.0,8.0,27.192982,24.561404
24,Team 25,553.0,520.0,633.0,0.0,0.0,6.0,32.236842,24.561404
42,Team 43,148.0,155.0,253.0,0.0,0.0,17.0,24.342105,24.342105
20,Team 21,970.0,892.0,789.0,0.0,1.0,2.0,41.176471,26.625387
47,Team 48,83.0,62.0,117.0,0.0,0.0,17.0,25.000000,28.750000
48,Team 49,81.0,70.0,115.0,0.0,0.0,19.0,23.750000,30.000000
38,Team 39,190.0,199.0,241.0,0.0,0.0,10.0,32.500000,28.125000
35,Team 36,277.0,320.0,410.0,0.0,0.0,7.0,28.148148,28.148148
45,Team 46,96.0,101.0,139.0,0.0,0.0,9.0,22.807018,38.596491
33,Team 34,293.0,291.0,489.0,0.0,0.0,7.0,27.745665,26.589595
52,Team 53,52.0,71.0,116.0,0.0,0.0,10.0,25.000000,26.470588
39,Team 40,188.0,202.0,296.0,0.0,0.0,8.0,26.881720,24.731183
22,Team 23,662.0,760.0,1088.0,0.0,0.0,8.0,28.987730,22.699387
32,Team 33,343.0,393.0,662.0,0.0,0.0,12.0,23.214286,28.348214
30,Team 31,375.0,422.0,581.0,0.0,0.0,7.0,29.078014,24.113475
40,Team 41,168.0,216.0,310.0,0.0,0.0,12.0,28.921569,24.509804
29,Team 30,416.0,430.0,632.0,0.0,0.0,6.0,28.109453,23.631841
41,Team 42,150.0,165.0,221.0,0.0,0.0,7.0,29.444444,24.444444
37,Team 38,230.0,285.0,430.0,0.0,0.0,5.0,29.078014,22.340426
26,Team 27,510.0,619.0,744.0,0.0,0.0,5.0,31.376518,25.910931
18,Team 19,1148.0,1182.0,1371.0,0.0,0.0,3.0,33.704453,25.910931
23,Team 24,606.0,750.0,1022.0,0.0,0.0,5.0,29.941003,26.548673
57,Team 58,22.0,37.0,57.0,0.0,0.0,16.0,23.333333,26.666667
59,Team 60,14.0,34.0,65.0,0.0,0.0,15.0,16.666667,13.333333
50,Team 51,71.0,121.0,183.0,0.0,0.0,14.0,32.222222,14.444444
58,Team 59,19.0,51.0,85.0,0.0,0.0,16.0,23.333333,16.666667
19,Team 20,1020.0,1347.0,1746.0,0.0,1.0,2.0,33.485401,22.080292
54,Team 55,40.0,70.0,182.0,0.0,0.0,16.0,19.117647,20.588235
16,Team 17,1314.0,1421.0,1763.0,0.0,0.0,4.0,31.075697,26.294821
12,Team 13,1471.0,1767.0,2180.0,0.0,0.0,4.0,31.582538,26.193724
46,Team 47,91.0,181.0,295.0,0.0,0.0,7.0,29.310345,13.793103
49,Team 50,76.0,145.0,252.0,0.0,0.0,10.0,27.777778,14.814815
14,Team 15,1389.0,1753.0,2152.0,0.0,1.0,2.0,32.304527,24.554184
31,Team 32,353.0,492.0,720.0,0.0,0.0,4.0,30.281690,22.300469
21,Team 22,667.0,819.0,1157.0,0.0,0.0,6.0,29.380054,23.584906
34,Team 35,285.0,419.0,588.0,0.0,0.0,4.0,30.838323,23.652695
10,Team 11,1814.0,2052.0,2188.0,1.0,5.0,1.0,36.797386,25.620915
27,Team 28,445.0,607.0,992.0,0.0,0.0,11.0,24.744027,24.402730
8,Team 9,2109.0,2683.0,2847.0,0.0,1.0,2.0,35.146022,26.283988
11,Team 12,1789.0,2278.0,2624.0,0.0,0.0,4.0,34.511190,22.909305
25,Team 26,538.0,716.0,1050.0,0.0,0.0,5.0,29.299363,23.726115
15,Team 16,1351.0,1500.0,1834.0,0.0,0.0,4.0,32.321700,24.810319
5,Team 6,2819.0,3680.0,3373.0,1.0,4.0,1.0,41.112957,22.051495
17,Team 18,1174.0,1642.0,1951.0,0.0,0.0,3.0,34.228188,24.496644
9,Team 10,1884.0,2159.0,2492.0,1.0,0.0,1.0,35.069444,25.462963
3,Team 4,3386.0,4398.0,3469.0,6.0,6.0,1.0,44.557057,23.123123
28,Team 29,421.0,458.0,623.0,0.0,0.0,6.0,32.894737,21.315789
13,Team 14,1416.0,1843.0,2368.0,0.0,1.0,2.0,31.722689,23.529412
7,Team 8,2573.0,3228.0,3230.0,2.0,3.0,1.0,37.532580,25.065161
44,Team 45,107.0,227.0,308.0,0.0,0.0,3.0,33.076923,16.153846
51,Team 52,56.0,153.0,184.0,0.0,0.0,6.0,29.166667,19.444444
4,Team 5,3368.0,4631.0,3700.0,8.0,7.0,1.0,43.772629,22.918175
53,Team 54,42.0,97.0,131.0,0.0,0.0,8.0,33.333333,11.111111
2,Team 3,3442.0,4534.0,3309.0,10.0,8.0,1.0,47.475134,22.876817
6,Team 7,2792.0,3609.0,3889.0,0.0,0.0,3.0,36.100533,23.153085